<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Common extends Model{
    
    public static $securityQuestionOne = [
        '01' => 'What was your childhood nickname?',
        '02' => 'What is the name of your favorite childhood friend?',
        '03' => 'In what city does your nearest sibling live?'
    ];

    public static $securityQuestionTwo = [
        '01' => 'In what city or town was your first job?',
        '02' => 'What was the last name of your third grade teacher?',
        '03' => 'In what city or town did your mother and father meet?'
    ];

    public static $gender = [
        'F' => 'Female',
        'M' => 'Male'
    ];

    public static $role = [
        '01' => 'Doctor',
        '02' => 'Nurse'
    ];

    public static $cancer = [
        '01' => 'Leukemia',
        '02' => 'Lymphoma',
        '03' => 'Brain Cancer'
    ];

    public static $relation = [
        '01' => 'Parents',
        '02' => 'Guardians'
    ];

    public static $state = [
        '01' => 'Perlis',
        '02' => 'Kedah',
        '03' => 'Perak',
        '04' => 'Kelantan',
        '05' => 'Terengganu',
        '06' => 'Pahang',
        '07' => 'Penang',
        '08' => 'Selangor',
        '09' => 'Melaka',
        '10' => 'Negeri Sembilan',
        '11' => 'Johor',
        '12' => 'Sarawak',
        '13' => 'Sabah',
    ];

    public static $age = [
        '07' => '7',
        '08' => '8',
        '09' => '9',
        '10' => '10',
        '11' => '11', 
    ];

    public static $hospitals = [
        // johor
        'J001' => 'Hospital Pakar Sultanah Fatimah',
        'J002' => 'Hospital Sultanah Nora Ismail',
        'J003' => 'Hospital Enche Besar Hajjah Kalsom',
        'J004' => 'Hospital Segamat',
        'J005' => 'Hospital Pontian',
        'J006' => 'Hospital Kota Tinggi',
        'J007' => 'Hospital Mersing',
        'J008' => 'Hospital Tangkak',
        'J009' => 'Hospital Temenggung Seri Maharaja Tun Ibrahim',
        'J010' => 'Hospital Permai Johor Bahru',
        'J011' => 'Sultan Ismail Hospital',
        'J012' => 'Hospital Sultanah Aminah',
        'J013' => 'Landmark Medical Centre Sdn Bhd',
        'J014' => 'KPJ Johor Specialist Hospital',
        'J015' => 'KPJ Kluang Utama Specialist Hospital',
        'J016' => 'Columbia Asia Hospital',
        'J017' => 'Hospital Penawar',
        'J018' => 'Pantai Hospital Batu Pahat',
        'J019' => 'Putra Specialist Hospital',
        'J020' => 'KPJ Batu Pahat Specialist Hospital',
        'J021' => 'Puteri Specialist Hospital',
        'J022' => 'KPJ Bandar Maharani Specialist Hospital (Muar)',
        'J023' => 'KPJ Pasir Gudang Specialist Hospital',
        'J024' => 'Regency Specialist Hospital',
        'J025' => 'Hospital Gleneagles Medini',
        'J026' => 'Hospital Pakar Skudai',
        'J027' => 'Kempas Medical Centre',
        'J028' => 'Columbia Asia Hospital',
        'J029' => 'KPJ Bandar Dato\' Onn Specialist Hospital',
        'J030' => 'Hospital Pasir Gudang',
        
        // kedah
        'K001' => 'Sultanah Bahiyah Hospital',
        'K002' => 'Sultan Abdul Halim Hospital',
        'K003' => 'Kulim Hospital',
        'K004' => 'Baling Hospital',
        'K005' => 'Sik Hospital',
        'K006' => 'Langkawi Hospital',
        'K007' => 'Hospital Yan',
        'K008' => 'Hospital Jitra',
        'K009' => 'Hospital Kuala Nerang',
        'K010' => 'Pantai Hospital Sungai Petani',
        'K011' => 'Kedah Medical Centre',
        'K012' => 'Putra Medical Centre',
        'K013' => 'Mahsuri Medical Centre',
        'K014' => 'Metro Specialist Hospital',
        'K015' => 'Amanjaya Specialist Hospital',
        'K016' => 'Ins Specialist Centre',

        // kelantan
        'D001' => 'Hospital Raja Perempuan Zainab II',
        'D002' => 'Hospital Pasir Mas',
        'D003' => 'Hospital Tumpat',
        'D004' => 'Hospital Machang',
        'D005' => 'Hospital Jeli',
        'D006' => 'Hospital Tanah Merah',
        'D007' => 'Hospital Tengku Anis',
        'D008' => 'Hospital Gua Musang',
        'D009' => 'Hospital Kuala Krai',
        'D010' => 'Hospital Universiti Sains Malaysia (HUSM)',
        'D011' => 'Pusat Rawatan Islam An-Nisa',
        'D012' => 'Kota Bharu Medical Centre',
        'D013' => 'Perdana Specialist Hospital',
        'D014' => 'Telipot Medical Centre',
        'D015' => 'Hospital USAINS, USM',

        // kuala lumpur
        'W001' => 'Hospital Angkatan Tentera Tuanku Mizan',
        'W002' => 'Hospital Rehabilitasi Cheras',
        'W003' => 'Kuala Lumpur Hospital',
        'W004' => 'Universiti Kebangsaan Malaysia Medical Centre (PPUKM)',
        'W005' => 'University Malaya Specialist Centre (UMSC)',
        'W006' => 'University Malaya Medical Centre',
        'W007' => 'iHEAL Medical Centre',
        'W008' => 'Columbia Asia Hospital',
        'W009' => 'Global Doctors Specialist Centre',
        'W010' => 'Columbia Asia Hospital',
        'W011' => 'Prince Court Medical Centre',
        'W012' => 'ALPS Medical Centre',
        'W013' => 'Institut Jantung Negara/National Heart Institute of Malaysia (IJN)',
        'W014' => 'Sunway Medical Centre',
        'W015' => 'Gleneagles Kuala Lumpur',
        'W016' => 'Damai Service Hospital',
        'W017' => 'Sentosa Medical Centre',
        'W018' => 'Tung Shin Hospital',
        'W019' => 'Pantai Medical Centre',
        'W020' => 'Lourdes Medical Centre',
        'W021' => 'Poliklinik Mallal Ear,Nose,Throat Clinic',
        'W022' => 'Sambhi Clinic & Nursing Home',
        'W023' => 'Damai Service Hospital',
        'W024' => 'Samuel Clinic & Specialist Maternity & Clinic for Women',
        'W025' => 'Pusat Rawatan Islam S/B',
        'W026' => 'Roopi Medical Centre',
        'W027' => 'Pusat Pakar Tawakal S/B',
        'W028' => 'KPJ Tawakkal Specialist Hospital',
        'W029' => 'Chinese Maternity Hospital',
        'W030' => 'Pantai Cheras Medical Centre',
        'W031' => 'Taman Desa Medical Centre',
        'W032' => 'Cheras Geriatric Centre',
        'W033' => 'Apollo TTDI Medical Centre',
        'W034' => 'Poliklinik Kotaraya',
        'W035' => 'Sentul Hospital',
        'W036' => 'Hospital Pantai Indah',
        'W037' => 'Hospital Danau Kota',
        'W038' => 'Pudu Specialist Centre',
        'W039' => 'Al-Islam Medical Centre',
        'W040' => 'Clinic Rosman',
        'W041' => 'onemedcare',
        'W042' => 'UKM Specialist Centre',
        'W043' => 'KPJ Ampang Puteri Specialist Hospital',
        'W044' => 'Beacon Hospital, Petaling Jaya',

        // labuan
        'L001' => 'Hospital Nukleus Labuan',
        'L002' => 'Jabatan Kesihatan Labuan',

        // melaka
        'M001' => 'Melaka General Hospital',
        'M002' => 'Hospital Alor Gajah',
        'M003' => 'Hospital Jasin',
        'M004' => 'Pantai Hospital Ayer Keroh',
        'M005' => 'Mahkota Medical Centre',
        'M006' => 'Putra Specialist Hospital (Melaka)',
        'M007' => 'Oriental Melaka Straits Medical Centre',

        // negeri sembilan
        'N001' => 'Tuanku Ja\'afar Hospital',
        'N002' => 'Hospital Tuanku Ampuan Najihah',
        'N003' => 'Hospital Port Dickson',
        'N004' => 'Hospital Tampin',
        'N005' => 'Hospital Jelebu',
        'N006' => 'Hospital Jempol',
        'N007' => 'Hospital Rembau',
        'N008' => 'Columbia Asia Hospital',
        'N009' => 'Nilai Medical Centre',
        'N010' => 'Seremban Specialist Hospital',
        'N011' => 'Senawang Specialist Hospital',
        'N012' => 'Mawar Medical Centre',
        'N013' => 'NSCMH Medical Centre',

        // pahang
        'C001' => 'Tengku Ampuan Afzan Hospital',
        'C002' => 'Hospital Pekan',
        'C003' => 'Hospital Kuala Lipis',
        'C004' => 'Hospital Raub',
        'C005' => 'Hospital Bentong',
        'C006' => 'Hospital Jerantut',
        'C007' => 'Hospital Jengka',
        'C008' => 'Hospital Muadzam Shah',
        'C009' => 'Hospital Sultan Haji Ahmad Shah',
        'C010' => 'Hospital Cameron Highlands',
        'C011' => 'Hospital Rompin',
        'C012' => 'Hospital Universiti Islam Antabangsa (UIA) Kuantan',
        'C013' => 'Darul Makmur Medical Centre Sdn. Bhd',

        // penang
        'P001' => 'Penang General Hospital',
        'P002' => 'Hospital Sungai Bakap',
        'P003' => 'Hospital Bukit Mertajam',
        'P004' => 'Hospital Balik Pulau',
        'P005' => 'Hospital Seberang Jaya',
        'P006' => 'Hospital Kepala Batas',
        'P007' => 'Mount Miriam Cancer Hospital',
        'P008' => 'Penang Adventist Hospital',
        'P009' => 'Carl Corrynton Medical Centre',
        'P010' => 'Lam Wah Ee Hospital',
        'P011' => 'Island Hospital',
        'P012' => 'Loh Guan Lye Specialists Centre',
        'P013' => 'Gleneagles Medical Centre',
        'P014' => 'KPJ Penang Specialist Hospital',
        'P015' => 'Bagan Specialist Centre',
        'P016' => 'Pantai Hospital Penang',

        // perak
        'A001' => 'Batu Gajah Hospital',
        'A002' => 'Hospital Bahagia Ulu Kinta',
        'A003' => 'Hospital Changkat Melintang',
        'A004' => 'Hospital Grik',
        'A005' => 'Hospital Kampar',
        'A006' => 'Hospital Kuala Kangsar',
        'A007' => 'Hospital Parit Buntar',
        'A008' => 'Hospital Raja Permaisuri Bainun',
        'A009' => 'Hospital Selama',
        'A010' => 'Hospital Seri Manjung',
        'A011' => 'Hospital Sg. Siput',
        'A012' => 'Hospital Slim River',
        'A013' => 'Hospital Tapah',
        'A014' => 'Hospital Taiping',
        'A015' => 'Hospital Teluk Intan',
        'A016' => 'Columbia Asia Hospital',
        'A017' => 'Fatimah Hospital',
        'A018' => 'Perak Chinese Maternity Hospital',
        'A019' => 'KPJ Ipoh Specialist Hospital',
        'A020' => 'Kinta Medical Centre',
        'A021' => 'Pantai Hospital Ipoh',
        'A022' => 'Pusat Pakar Rajindar Singh',
        'A023' => 'Anson Bay Medical Centre',
        'A024' => 'Maxwell Maternity & Surgical Centre',
        'A025' => 'Apollo Medical Centre',
        'A026' => 'Taiping Medical Centre',
        'A027' => 'Pantai Hospital Manjung',
        'A028' => 'KPJ Centre Manjung',

        // perlis
        'R001' => 'Hospital Tuanku Fauziah',
        'R002' => 'KPJ Perlis Specialist Hospital',

        // putrajaya
        'F001' => 'Hospital Putrajaya',
        'F002' => 'National Cancer Institute',

        // sabah
        'H001' => 'Queen Elizabeth Hospital, Kota Kinabalu (I & II)',
        'H002' => 'Duchess of Kent Hospital',
        'H003' => 'Hospital Beaufort',
        'H004' => 'Hospital Beluran',
        'H005' => 'Hospital Keningau',
        'H006' => 'Hospital Kinabatangan',
        'H007' => 'Hospital Kota Belud',
        'H008' => 'Hospital Kota Marudu',
        'H009' => 'Hospital Kuala Penyu',
        'H010' => 'Hospital Kudat',
        'H011' => 'Hospital Lahad Datu',
        'H012' => 'Hospital Mesra Bukit Padang',
        'H013' => 'Hospital Papar',
        'H014' => 'Hospital Ranau',
        'H015' => 'Hospital Semporna',
        'H016' => 'Hospital Sipitang',
        'H017' => 'Hospital Tambunan',
        'H018' => 'Hospital Tawau',
        'H019' => 'Hospital Tenom',
        'H020' => 'Hospital Wanita dan Kanak-Kanak Sabah',
        'H021' => 'KPJ Sabah Specialist Hospital',
        'H022' => 'KPJ Damai Specialist Centre',
        'H023' => 'Rafflesia Medical Centre',
        'H024' => 'Gleneagles Kota Kinabalu Hospital',
        'H025' => 'Jesselton Medical Centre',
        'H026' => 'Tawau Specialist Medical Centre',

        // sarawak
        'V001' => 'Sarawak General Hospital',
        'V002' => 'Sarawak General Hospital, Kota Samarahan',
        'V003' => 'Hospital Bau',
        'V004' => 'Hospital Sibu',
        'V005' => 'Hospital Miri',
        'V006' => 'Hospital Sarikei',
        'V007' => 'Hospital Sri Aman',
        'V008' => 'Hospital Limbang',
        'V009' => 'Hospital Lawas',
        'V010' => 'Hospital Kapit',
        'V011' => 'Hospital Sentosa',
        'V012' => 'Hospital Mukah',
        'V013' => 'Hospital Marudi',
        'V014' => 'Hospital Lundu',
        'V015' => 'Hospital Bintulu',
        'V016' => 'Hospital Betong',
        'V017' => 'Hospital Serian',
        'V018' => 'Hospital Simunjan',
        'V019' => 'Rajah Charles Brooke Memorial Hospital',
        'V020' => 'Hospital Kanowit',
        'V021' => 'Hospital Saratok',
        'V022' => 'Hospital Sri Aman',
        'V023' => 'Hospital Dalat',
        'V024' => 'Columbia Asia Hospital - Bintulu',
        'V025' => 'Columbia Asia Hospital - Miri',
        'V026' => 'KPJ Sibu Specialist Medical Centre',
        'V027' => 'Rejang Medical Centre',
        'V028' => 'Normah Medical Specialist Centre',
        'V029' => 'Kuching Specialist Hospital',
        'V030' => 'Timberland Medical Centre',
        'V031' => 'Borneo Medical Centre',
        'V032' => 'Miri City Medical Centre',
        'V033' => 'Bintulu Medical Centre',
        'V034' => 'KPJ Miri Specialist Hospital',

        // selangor
        'S001' => 'Hospital Shah Alam',
        'S002' => 'Hospital Ampang',
        'S003' => 'Hospital Banting',
        'S004' => 'Hospital Kajang',
        'S005' => 'Hospital Kuala Kubu Baru',
        'S006' => 'Hospital Selayang',
        'S007' => 'Hospital Serdang',
        'S008' => 'Hospital Sungai Buloh',
        'S009' => 'Hospital Tanjung Karang',
        'S010' => 'Hospital Tengku Ampuan Jemaah',
        'S011' => 'Hospital Tengku Ampuan Rahimah',
        'S012' => 'Alpha Specialist Centre',
        'S013' => 'Beacon Hospital, Petaling Jaya',
        'S014' => 'Columbia Asia Hospital - Bukit Rimau',
        'S015' => 'Columbia Asia Hospital - Cheras',
        'S016' => 'Columbia Asia Hospital - Klang',
        'S017' => 'Columbia Asia Hospital - Petaling Jaya',
        'S018' => 'Columbia Asia Hospital - Puchong',
        'S019' => 'Columbia Asia Extended Care Hospital - Shah Alam',
        'S020' => 'Thomson Hospital, Kota Damansara',
        'S021' => 'NR Pusat Diagnostik',
        'S022' => 'Sentosa Medical Centre',
        'S023' => 'Assunta Hospital',
        'S024' => 'Tun Hussein Onn National Eye Hospital',
        'S025' => 'Subang Jaya Medical Centre',
        'S026' => 'BP Specialist Centre Taman Megah',
        'S027' => 'Ampang Puteri Specialist Hospital',
        'S028' => 'Damansara Specialist Hospital',
        'S029' => 'Puteri Klang Medical Centre',
        'S030' => 'Selangor Medical Centre',
        'S031' => 'QHC Medical Centre',
        'S032' => 'Hospital Wanita Metro Klang',
        'S033' => 'KPJ Selangor Specialist Hospital',
        'S034' => 'Klinik Pakar Wanita Sheela & Rumah Bersalin',
        'S035' => 'Lam Surgery & Maternity Home S/B',
        'S036' => 'Kajang Specialist Maternity & Surgery S/B',
        'S037' => 'Sunway Medical Centre',
        'S038' => 'Kelana Jaya Medical Centre',
        'S039' => 'Darul Ehsan Medical Centre, Shah Alam',
        'S040' => 'Salam Medical Centre',
        'S041' => 'Metro IVF Centre',
        'S042' => 'Pusat Rawatan Islam (MAIS) S/B',
        'S043' => 'PJ Nursing Home',
        'S044' => 'Hospital UMRA',
        'S045' => 'Hospital Wanita Metro Banting',
        'S046' => 'Shah Alam Medical Centre',
        'S047' => 'Andalas Medical Centre',
        'S048' => 'PMMC, Shah Alam',
        'S049' => 'Putra Medical Centre, Sungai Buloh',
        'S050' => 'University Malaya Specialist Centre',
        'S051' => 'Metro Maternity Kuala Selangor',
        'S052' => 'Manipal Hospitals Klang, Bandar Bukit Tinggi, Klang',
        'S053' => 'Pantai Hospital Klang',
        'S054' => 'Sri Kota Medical Centre, Klang',
        'S055' => 'Klang Specialist Hospital',
        'S056' => 'Andorra Women and Children Hospital',

         // terengganu
        'T001' => 'Hospital Sultanah Nur Zahirah',
        'T002' => 'Hospital Dungun',
        'T003' => 'Hospital Kemaman',
        'T004' => 'Hospital Besut',
        'T005' => 'Hospital Hulu Terengganu',
        'T006' => 'Hospital Setiu',
        'T007' => 'Kuala Terengganu Specialist Hospital',
        'T008' => 'SALAM Specialist Hospital Kuala Terengganu'
    ];
}